// Tab 3: pre-meeting brief card — auto-generated by the bot before a booked call
import { CalendarClock, User, AlertTriangle } from 'lucide-react'
import { brief } from '../../data/brief.js'
import Card from '../common/Card.jsx'
import Badge from '../common/Badge.jsx'

export default function MeetingBrief() {
  return (
    <Card className="max-w-2xl overflow-hidden">
      <div className="border-b border-slate-200 bg-slate-900 p-5 text-white">
        <p className="text-xs font-semibold uppercase tracking-wider text-blue-300">
          Pre-Meeting Brief · generated by HelpSense
        </p>
        <h3 className="mt-1 text-lg font-bold">{brief.meetingWith}</h3>
        <div className="mt-2 flex flex-wrap gap-4 text-xs text-slate-300">
          <span className="flex items-center gap-1.5">
            <CalendarClock size={13} /> {brief.scheduledFor}
          </span>
          <span className="flex items-center gap-1.5">
            <User size={13} /> For: {brief.supportPerson}
          </span>
        </div>
      </div>

      <div className="space-y-5 p-5">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Issue summary · {brief.module}</p>
          <p className="mt-1.5 text-sm text-slate-700">{brief.issueSummary}</p>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Past tickets ({brief.client})</p>
          <div className="mt-2 space-y-1.5">
            {brief.pastTickets.map((t) => (
              <div key={t.id} className="flex items-center gap-3 rounded-lg bg-slate-50 px-3 py-2">
                <span className="text-xs font-bold text-slate-400">{t.id}</span>
                <span className="flex-1 truncate text-sm text-slate-700">{t.title}</span>
                <Badge label={t.status} />
              </div>
            ))}
          </div>
        </div>

        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Suggested plan</p>
          <ol className="mt-2 space-y-1.5">
            {brief.suggestedPlan.map((step, i) => (
              <li key={step} className="flex gap-2.5 text-sm text-slate-700">
                <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-blue-50 text-xs font-bold text-blue-600">
                  {i + 1}
                </span>
                {step}
              </li>
            ))}
          </ol>
        </div>

        <div className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5">
          <AlertTriangle size={14} className="shrink-0 text-red-500" />
          <p className="text-xs font-semibold text-red-700">Sentiment: {brief.sentiment}</p>
        </div>
      </div>
    </Card>
  )
}
